---

- name: download and unarchive istio
  unarchive:
    src: '{{ _link_istio }}'
    dest: '/opt/istio'
    remote_src: true

- name: create namespace istio
  shell: kubectl create namespace istio-system

- name: initalize istio with helm
  shell: helm install /opt/istio/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system

- name: waiting istio
  shell: kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | wc -l
  register: istio_init
  until: istio_init.stdout == 53
  retries: 5
  delay: 2

- name: status istio
  debug:
    msg: "Istio ready!"

- include: install-kiali.yml
  when: kiali_install == true
